### ISSUE TITLE
CSS Updating

### ISSUE THREAD

**Issue by Jacke** [Empia/minorityapp#4]
``` css
.use-cases.content-23 .hero-unit h1 {
    padding-top: 20px;
}

.use-cases.content-23 .hero-unit {
    border-radius: 0;
}

.hero-unit {}


section.content-23.use-cases.v-center.bg-midnight-blue {
  padding-top: 104px !important;
  background-repeat: no-repeat;
  background-size: contain;
  background: -webkit-linear-gradient(top, #58488a, #6299c9);
  background: linear-gradient(to bottom, #58488a, #6299c9);
  margin-top: 0px !important;
}
.use-cases .examples {
  display: block;
  padding-bottom: 35px;
}


.use-cases .conclusion {
    position: relative;   display: block;   
    padding: 5px 0px 19px 0px;   margin: 0;   text-decoration: none;   font-weight: 200;   text-align: center;   background: #F8F8F8;   color: #444;   font-size: 19px;   border-bottom: 1px solid #EBEBEB;
    margin-bottom: -20px;
}
.use-cases .conclusion h5 {
    margin-bottom: -20px;
    padding-bottom: 20px;
    font-size: 18px;
    padding-top: 9px;
}
```
